version: '3.8'

services:
  fallback_reduction:
    build: ./Fallback_Reduction
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./Fallback_Reduction/:/app/
      - ~/.aws/:/root/.aws:ro
    ports:
      - 8001:8000
    environment:
      - AWS_PROFILE=default


  next_query_recommendation:
    build: ./Next_Query_Recommendation
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./Next_Query_Recommendation/:/app/
      - ~/.aws/:/root/.aws:ro
    ports:
      - 8002:8000
    environment:
      - AWS_PROFILE=default


  query_expansion:
    build: ./Query_Expansion
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./Query_Expansion/:/app/
      - ~/.aws/:/root/.aws:ro
    ports:
      - 8003:8000
    environment:
      - AWS_PROFILE=default

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fallback_reduction
      - next_query_recommendation
      - query_expansion