apiVersion: v1
kind: Namespace
metadata:
  name: qe
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: qe
  name: app-qe
spec:
  selector:
    matchLabels:
      app: app-qe
      env: qe
  replicas: 1
  template:
    metadata:
      labels:
        app: app-qe
        env: qe
    spec:
      containers:
      - image: 147642600964.dkr.ecr.ap-south-1.amazonaws.com/nqr-eks:latest
        imagePullPolicy: Always
        command: [ "sleep" ]
        args: [ "infinity" ]
        name: app-qe
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  namespace: qe
  name: service-qe
spec:
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  type: NodePort
  selector:
    app: app-qe
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: qe
  name: ingress-qe
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/subnets: subnet-01328f78ac285b3f3,subnet-0abe81172d8c421a1
    
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: service-qe
              servicePort: 8000





